- name: Retrieve required AWS infrastructure ID's 
  block:
    - name: retrieve vpc ID                 
      amazon.aws.ec2_vpc_net_info:
        profile: "{{ aws_profile | default('') }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        filters:
          "tag:demo": Ansible
      register: vpc_info 

    - name: retrieve vpc subnet info 
      amazon.aws.ec2_vpc_subnet_info:
        profile: "{{ aws_profile | default('') }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        filters:
          "tag:demo": Ansible
      register: vpc_subnet_info

    - name: retrieve vpc route table id 
      community.aws.ec2_vpc_route_table_info:
        profile: "{{ aws_profile | default('') }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        filters:
          "tag:demo": Ansible
      register: vpc_route_info

    - name: Retrieve Security Group info 
      amazon.aws.ec2_group_info:
        profile: "{{ aws_profile | default('') }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        filters:
          "tag:demo": Ansible
      register: sec_info