--- 
ansible_user: ec2-user 
controller_dns: controller.{{ top_level_domain }}
sso_dns: sso.{{ top_level_domain }}
catalog_dns: catalog.{{ top_level_domain }}
hub_dns: hub.{{ top_level_domain }}

acme_env: 
  staging: https://acme-staging-v02.api.letsencrypt.org/directory
  prod: https://acme-v02.api.letsencrypt.org/directory

controller_hostname: https://{{ controller_dns }}
controller_username: admin 
controller_password: "{{ admin_password }}"

hub_offline_token: "{{ lookup('ini', 'token section=galaxy_server.automation_hub file=ansible.cfg') }}"