---
collections:
# Galaxy Collections
  - name: community.crypto 
    version: 2.5.0 
  - name: community.general 
    version: 5.5.0 
  - name: community.aws 
    version: 3.5.0 
  # - name: redhat_cop.controller_configuration
  #   version: 2.1.7
# Automation Hub Collections 
  - name: ansible.posix 
    version: 1.4.0
  - name: ansible.controller 
    version: 4.2.0
  - name: servicenow.itsm 
    version: 1.4.0
  - name: community.hashi_vault 
    version: 3.3.1
