---
- name: Create new Project in EDA Controller 
  ansible.builtin.uri:
    url: https://eda.{{ top_level_domain }}/api/eda/v1/projects/
    method: GET 
    user: admin 
    password: "{{ admin_password }}"
    force_basic_auth: true 
    status_code: 200 
  register: eda_projects 

- name: Create new Project in EDA Controller 
  ansible.builtin.uri:
    url: https://eda.{{ top_level_domain }}/api/eda/v1/projects/
    method: POST 
    user: admin 
    password: "{{ admin_password }}"
    force_basic_auth: true 
    body_format: json 
    body: 
      name: "AAP EDA Demo"
      url: "https://github.com/corumj/aap-demo.git"
    status_code: 201 
  when: eda_projects | regex_findall('AAP EDA Demo') | length == 0
  register: new_project 

- name: Create new Controller token in EDA Controller 
  ansible.builtin.uri:
    url: https://eda.{{ top_level_domain }}/api/eda/v1/users/me/awx-tokens/
    method: GET 
    user: admin 
    password: "{{ admin_password }}"
    force_basic_auth: true 
    status_code: 200 
  register: eda_controller_tokens 

- name: Create new Controller token in EDA Controller 
  ansible.builtin.uri:
    url: https://eda.{{ top_level_domain }}/api/eda/v1/users/me/awx-tokens/
    method: POST 
    user: admin 
    password: "{{ admin_password }}"
    force_basic_auth: true 
    body_format: json 
    body: 
      name: "Controller Token"
      token: "{{ eda_token.ansible_facts.controller_token.token }}"
    status_code: 201 
  when: eda_controller_tokens | regex_findall('Controller Token') | length == 0 