- name: Start AAP Servers 
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:

    - name: Start Instances 
      amazon.aws.ec2_instance:
        wait: yes
        region: "{{ aws_region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        state: started
        filters:
          instance-state-name: stopped

    - name: Wait for instances to pass EC2 checks 
      pause:
        seconds: 30

    - meta: refresh_inventory

    - name: Update DNS with new IPs 
      include_role: 
        name: certificates
        tasks_from: set-dns.yml

- name: Start Controller Service
  hosts: demo_controller 
  gather_facts: no 
  become: yes 

  tasks: 
    - name: Start AAP service 
      service:
        name: automation-controller 
        state: started  

    - name: Access Apps 
      debug:
        msg: 
          - "Automation Controller: https://{{ controller_dns }} "
          - "Automation Hub: https://{{ hub_dns }} "
          - "EDA Controller: https://{{ eda_dns }} "