- name: Shutdown Controller 
  hosts: demo_controller 
  gather_facts: no 
  become: yes 

  tasks: 
    - name: Shut down AAP service 
      service:
        name: automation-controller 
        state: stopped 

- name: Shutdown AAP infrastructure 
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
    - name: Shut Down All Instances 
      amazon.aws.ec2_instance:
        state: stopped
        filters:
          instance-state-name: running