--- 
- name: Deploy Kafka in a container 
  hosts: demo_kafka 
  gather_facts: no 

  tasks: 
    - name: Ensure podman is installed 
      ansible.builtin.package:
        name: podman 
        state: latest 
      become: yes 

    - name: Start container 
      containers.podman.podman_container:
        name: kafka-server 
        image: docker.io/bitnami/kafka:3.5
        state: started 
        ports:
          - "9092:9092"
          - "9094:9094"
        env:
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://{{ inventory_hostname }}:9094
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT   
