---
- name: Get Pod info from OCP 
  hosts: localhost 

  vars: 
    ocp_username: "{{ ansible_user }}"
    ocp_password: "{{ ansible_password }}"

  tasks:
    - name: Authenticate to OCP 
      redhat.openshift.openshift_auth:
        username: "{{ ocp_username }}"
        password: "{{ ocp_password }}"
        host: https://api.cluster-wjrt5.wjrt5.sandbox2082.opentlc.com:6443
      register: openshift_auth_results

    - name: Get a list of all pods from any namespace
      kubernetes.core.k8s_info:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        kind: Pod
        host: https://api.cluster-wjrt5.wjrt5.sandbox2082.opentlc.com:6443
      register: pod_list