---
- name: Caching Facts Update ServiceNow CMDB from Ansible Facts 
  hosts: all 
  gather_facts: yes
  collections:  
    - ansible.builtin 

  tasks: 
    - name: Running to cache facts 
      debug:
        msg: "Caching Facts, please wait until complete."
      run_once: True 
      delegate_to: locahost 