---
- name: Caching Facts Update ServiceNow CMDB from Ansible Facts 
  hosts: all 
  gather_facts: true

  tasks: 
    - name: Running to cache facts 
      ansible.builtin.debug:
        msg: "Caching Facts, please wait until complete."
