---
- name: Use ansible facts to update ServiceNow CMDB 
  hosts: all 
  gather_facts: true

  tasks: 
    - name: Create a configuration item
      servicenow.itsm.configuration_item:
        name: ansible_fqdn
        serial_number: ansible_machine_id
        sys_class_name: cmdb_ci_server
        assigned_to: admin
        environment: dev
        category: Virtual Machine