---
- name: Scan for existing systems that are not in SNOW CMDB and Add them 
  hosts: localhost 
  connection: local 
  collections:  
    - servicenow.itsm 
    - amazon.aws 

  tasks: 
    - name: Retrieve instance information from AWS 
      ec2_instance_info: 
      register: ec2_instances 

 ##     IF instance already in SNOW, update, if not create? 

    - name: check for existing CMDB entry 
      configuration_item_info: 
        sys_class_name: cmdb_ci_ec2_instance
        query:
          - vm_inst_id: = "{{ item.instance_id }}"
        instance: 
          host: https://{{ servicenow_instance }}.service-now.com
          username: "{{ servicenow_username }}"
          password: "{{ servicenow_password }}"
      register: existing_cmdb 
      loop: "{{ ec2_instances.instances }}"

    - debug: 
        msg: "{{ item.records }}"
      loop: "{{ existing_cmdb.results }}"

      

    # - name: Print 
    #   debug:
    #     msg: "{{ item.tags.server_env }}"
    #   loop: "{{ ec2_instances.instances }}"

    # - name: Create a configuration item
    #   configuration_item:
    #     name: "{{ item.tags.Name }}"
    #     short_description: "{{ item.tags.short_desc }}"
    #     sys_class_name: cmdb_ci_ec2_instance
    #     assigned_to: admin
    #     environment: "{{ item.tags.server_env }}"
    #     category: Hardware
    #     ip_address: "{{ item.public_ip_address }}"
    #     other:
    #       vm_inst_id: "{{ item.instance_id }}"
    #     instance: 
    #       host: https://{{ servicenow_instance }}.service-now.com
    #       username: "{{ servicenow_username }}"
    #       password: "{{ servicenow_password }}"
    #   loop: "{{ ec2_instances.instances }}"

# - name: Update a configuration item
#   servicenow.itsm.configuration_item:
#     sys_id: "{{ server.record.sys_id }}"
#     install_status: in_maintenance
#     operational_status: repair_in_progress
#     other:
#       fault_count: 1
#       classification: Development

# - name: Delete a configuration item
#   servicenow.itsm.configuration_item:
#     sys_id: "{{ server.record.sys_id }}"
#     state: absent