--- 
- name: Print a stat from previous workflow node
  hosts: all 

  tasks: 
    - name: Print stat from previous workflow node 
      debug: 
        msg: "Stat: There are {{ packages_installed_stat }} packages installed on {{ inventory_hostname }}"

      # fact caching must be enabled on the fact gathering
      # playbook in order for the following to work 
    - name: Print cached fact from ansible_facts
      debug:
        msg: "Fact: There are {{ ansible_facts.packages_installed_fact }} packages installed on {{ inventory_hostname }}"
      when: ansible_facts.packages_installed_fact is defined 
      
    - name: Print cached hostvar 
      debug:
        msg: "Hostvar: There are {{ hostvars[inventory_hostname].packages_installed_fact }} packages installed on {{ inventory_hostname }}"