--- 
- name: Set a stat to retrieve in the next workflow playbook
  hosts: all 

  tasks: 

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

      # This will be passed as an extra_var to the next template
    - name: set stat
      ansible.builtin.set_stats:
        data:
          packages_installed_stat: "{{ ansible_facts.packages | length }}"

    # Setting cacheable=yes here means the fact is available in 
    # ansible_fact, without cacheable=yes, fact can only 
    # be retrieved as a hostvar (example in stats.pb2)
    - name: set fact 
      ansible.builtin.set_fact:
        packages_installed_fact: "{{ ansible_facts.packages | length }}"
        cacheable: yes  
