--- 
- name: Print a stat from previous workflow node
  hosts: all 

  tasks: 

      # with set_stats, just use the variable name from previous template
    - name: Print stat from previous workflow node 
      debug: 
        msg: "Stat: There are {{ packages_installed_stat }} packages installed on {{ inventory_hostname }}"

      # Fact caching must be enabled on the fact gathering job template
      # in order for the following to return a valid message 
    - name: Print cached fact from ansible_facts
      debug:
        msg: "Fact: There are {{ ansible_facts.packages_installed_fact }} packages installed on {{ inventory_hostname }}"
      when: ansible_facts.packages_installed_fact is defined 

      # if set_fact parameter cacheable=false, have to retrieve variable with hostvars
    - name: Print cached hostvar 
      debug:
        msg: "Hostvar: There are {{ hostvars[inventory_hostname].packages_installed_fact }} packages installed on {{ inventory_hostname }}"
      when: hostvars[inventory_hostname].packages_installed_fact is defined