--- 
- name: Set a stat to retrieve in the next workflow playbook
  hosts: all 

  tasks: 

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: set stat
      ansible.builtin.set_stats:
        data:
          packages_installed_stat: "{{ ansible_facts.packages | length }}"

    - name: set fact 
      ansible.builtin.set_fact:
        packages_installed_fact: "{{ ansible_facts.packages | length }}"
        cacheable: yes
