---
- name: Test fact caching with custom facts 
  hosts: node1 
  gather_facts: yes
  tasks:
    - name: set some fact 
      set_fact:
        pizza: 'pineapple'
        tech: 'biscuit'
        cacheable: true

    