---
- name: Create AWS Inventory 
  ansible.controller.inventory: 
    name: AWS
    description: AWS Inventory 
    organization: Default 
    state: present 
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://controller.{{ top_level_domain }}"
    validate_certs: true

- name: Create AWS Inventory Source
  ansible.controller.inventory_source:
    state: present  
    name: AWS 
    description: AWS inventory source 
    inventory: AWS  
    credential: AWS   
    overwrite: True  
    update_on_launch: True  
    source: ec2  
    source_vars: 
      filters:
        tag:demo: Ansible 
      keyed_groups:
        - key: tags['group_name']
          prefix: tag 
          parent_group: "demo"
        - key: tags['server_os']
          prefix: tag
          parent_group: os
      compose:
        ansible_host: private_ip_address
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://{{ controller_dns }}"
    validate_certs: false