---
- name: Create Ansible Demo Project
  ansible.controller.project:
    name: Ansible Demo 
    state: present
    wait: yes
    organization: Default 
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://controller.{{ top_level_domain }}"
    validate_certs: true
    scm_type: git 
    scm_url: https://github.com/corumj/ansible-demo.git
    scm_branch: OEwMesh
    scm_update_on_launch: yes 

- name: Create Provision Template
  ansible.controller.job_template:
    name: "1. Provision"
    job_type: "run"
    inventory: AWS
    project: Ansible Demo
    playbook: "provision.yml"
    credentials: 
      - "Controller Credential"
      - "AWS"
      - "AWS Windows"
    extra_vars:
      aws_profile: ''
    ask_variables_on_launch: yes
    use_fact_cache: yes
    allow_simultaneous: yes
    survey_enabled: yes 
    survey_spec: "{{ lookup('file', 'provision.json') }}"
    state: "present"
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://controller.{{ top_level_domain }}"
    validate_certs: true

- name: Create  Deprovision Template
  ansible.controller.job_template:
    name: "2. Deprovision"
    job_type: "run"
    inventory: AWS
    project: Ansible Demo
    playbook: "deprovision.yml"
    credentials: 
      - "Controller Credential"
      - "AWS"
    extra_vars:
      aws_profile: ''
    ask_variables_on_launch: yes
    allow_simultaneous: yes
    state: "present"
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://controller.{{ top_level_domain }}"
    validate_certs: true

- name: Remove Demo Job Template 
  ansible.controller.job_template:
    name: "Demo Job Template"
    organization: Default 
    inventory: AWS 
    project: Linux Tasks 
    state: absent 
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://controller.{{ top_level_domain }}"
    use_fact_cache: yes 