---
- name: Add {{ item.username }} to AAP Controller 
  ansible.controller.user:
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email }}"
    # superuser: yes
    state: present
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://controller.{{ top_level_domain }}"
    validate_certs: true

- name: Get EDA Controller Admin role UID 
  ansible.builtin.uri:
    url: https://eda.{{ top_level_domain }}/api/eda/v1/roles/
    method: GET 
    user: admin 
    password: "{{ admin_password }}"
    force_basic_auth: true 
    status_code: 200 
  register: eda_roles 

- name: Check if {{ item.username }} exists  in EDA Controller 
  ansible.builtin.uri:
    url: https://eda.{{ top_level_domain }}/api/eda/v1/users/
    method: GET 
    user: admin 
    password: "{{ admin_password }}"
    force_basic_auth: true 
  register: existing_users

- name: Add {{ item.username }} to EDA Controller 
  vars:
    query: "json.results[?name=='Admin'].id"
  ansible.builtin.uri:
    url: https://eda.{{ top_level_domain }}/api/eda/v1/users/
    method: POST 
    user: admin 
    password: "{{ admin_password }}"
    force_basic_auth: true 
    body_format: json 
    body: 
      username: "{{ item.username }}"
      password: "{{ item.password }}"
      roles: "{{ eda_roles | json_query(query) }}"
    status_code: 201 
  when: existing_users | regex_findall(item.username) | length == 0