## certificate related ssh keys/csr paths
acme_account_key_path: "{{ playbook_dir }}/generated_files/acme_key"
acme_private_key_path: "{{ playbook_dir }}/generated_files/cert_key"

controller_csr_path: "{{ playbook_dir }}/generated_files/{{ controller_dns }}"
sso_csr_path: "{{ playbook_dir }}/generated_files/{{ sso_dns }}"
catalog_csr_path: "{{ playbook_dir }}/generated_files/{{ catalog_dns }}"

