---
- name: Revoke certificate with account key
  community.crypto.acme_certificate_revoke:
    account_key_src: "{{ acme_account_key_path }}"
    certificate: "{{ playbook_dir }}/generated_files/{{ item }}.{{ top_level_domain}}_chain"
    acme_directory: "{{ acme_env[certificate_env] }}"
    acme_version: 2 
  loop:
    - "controller"
    - "hub"
    - "sso"
    - "catalog"