---
- name: Setup Route 53 for controller domain name 
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ controller_dns }}"
    type: A
    value: "{{ hostvars[groups['demo_controller'][0]]['public_ip_address'] }}"
    ttl: 300
    wait: yes
    overwrite: yes

- name: Setup Route 53 for Automation Hub domain name 
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ hub_dns }}"
    type: A
    value: "{{ hostvars[groups['demo_hub'][0]]['public_ip_address'] }}"
    ttl: 300
    wait: yes
    overwrite: yes

- name: Setup Route 53 for EDA Controller domain name 
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ eda_dns }}"
    type: A
    value: "{{ hostvars[groups['demo_eda'][0]]['public_ip_address'] }}"
    ttl: 300
    wait: yes
    overwrite: yes