---
- name: Setup automation controller dns check for acme challenge 
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ controller_challenge_record }}"
    type: TXT
    value: "{{ controller_challenge_value }}"
    ttl: 60
    wait: yes
    overwrite: yes
  when: 
    - controller_dns_challenge is changed 
    - controller_dns_challenge.challenge_data[controller_dns] is defined

- name: Setup SSO dns check for acme challenge 
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ sso_challenge_record }}"
    type: TXT
    value: "{{ sso_challenge_value }}"
    ttl: 60
    wait: yes
    overwrite: yes
  when: 
    - sso_dns_challenge is changed 
    - sso_dns_challenge.challenge_data[sso_dns] is defined

- name: Setup Services Catalog dns check for acme challenge 
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ catalog_challenge_record }}"
    type: TXT
    value: "{{ catalog_challenge_value }}"
    ttl: 60
    wait: yes
    overwrite: yes
  when: 
    - catalog_dns_challenge is changed 
    - catalog_dns_challenge.challenge_data[catalog_dns] is defined