---
- name: Validate Automation Controller DNS Challenge 
  acme_certificate:
    account_key_src: "{{ acme_account_key_path }}"
    account_email: "{{ cert_email }}"
    csr: "{{ controller_csr_path }}"
    dest: "{{ playbook_dir }}/generated_files/controller"
    fullchain_dest: "{{ playbook_dir }}/generated_files/controller.{{ top_level_domain}}_chain"
    challenge: dns-01 
    acme_directory: "{{ acme_env[certificate_env] }}"
    acme_version: 2 
    terms_agreed: yes 
    remaining_days: 10 
    data: "{{ controller_dns_challenge }}"
    force: "{{ certificate_force }}"
  register: controller_cert_valid
  when: 
    - controller_dns_challenge is changed 
    - controller_dns_challenge.challenge_data[controller_dns] is defined

- name: Validate Automation Hub DNS Challenge 
  acme_certificate:
    account_key_src: "{{ acme_account_key_path }}"
    account_email: "{{ cert_email }}"
    csr: "{{ hub_csr_path }}"
    dest: "{{ playbook_dir }}/generated_files/hub"
    fullchain_dest: "{{ playbook_dir }}/generated_files/hub.{{ top_level_domain}}_chain"
    challenge: dns-01 
    acme_directory: "{{ acme_env[certificate_env] }}"
    acme_version: 2 
    terms_agreed: yes 
    remaining_days: 10 
    data: "{{ hub_dns_challenge }}"
    force: "{{ certificate_force }}"
  register: hub_cert_valid
  when: 
    - hub_dns_challenge is changed 
    - hub_dns_challenge.challenge_data[hub_dns] is defined

- name: Validate EDA Controller DNS Challenge 
  acme_certificate:
    account_key_src: "{{ acme_account_key_path }}"
    account_email: "{{ cert_email }}"
    csr: "{{ eda_csr_path }}"
    dest: "{{ playbook_dir }}/generated_files/eda"
    fullchain_dest: "{{ playbook_dir }}/generated_files/eda.{{ top_level_domain}}_chain"
    challenge: dns-01 
    acme_directory: "{{ acme_env[certificate_env] }}"
    acme_version: 2 
    terms_agreed: yes 
    remaining_days: 10 
    data: "{{ eda_dns_challenge }}"
    force: "{{ certificate_force }}"
  register: eda_cert_valid
  when: 
    - eda_dns_challenge is changed 
    - eda_dns_challenge.challenge_data[eda_dns] is defined