---
- name: Setup Linux project 
  ansible.controller.project:
    name: Linux Tasks 
    state: present
    wait: yes
    organization: Default 
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true
    scm_type: git 
    scm_branch: platform
    scm_url: https://github.com/corumj/ansible-linux-tasks
    scm_update_on_launch: yes 

- name: Setup Patching Init playbook
  ansible.controller.job_template:
    name: "Linux - Patching Demo 1. Provision Servers"
    job_type: "run"
    inventory: AWS
    project: Linux Tasks
    playbook: "setup_patching_demo.yml"
    organization: Default 
    credentials: 
      - "Controller Credential"
      - "AWS"
      - "AWS Linux"
    # survey_enabled: yes 
    # survey_spec: "{{ lookup('file', 'servicenow.json') }}"
    state: "present"
    use_fact_cache: yes
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true