controller_credential_types:
  - name: SNOW
    description: ServiceNow credential type 
    kind: cloud
    inputs:
      fields:
        - id: username
          type: string
          label: SN_USERNAME
        - id: password
          type: string
          label: SN_PASSWORD
          secret: true 
        - id: instance 
          type: string
          label: SN_INSTANCE
    injectors:
      env:
        SN_INSTANCE: '{% raw %}{{ instance }}{% endraw %}'
        SN_PASSWORD: '{% raw %}{{ password }}{% endraw %}'
        SN_USERNAME: '{% raw %}{{ username }}{% endraw %}'
      extra_vars:
        SN_INSTANCE: '{% raw %}{{ instance }}{% endraw %}'
        SN_PASSWORD: '{% raw %}{{ password }}{% endraw %}'
        SN_USERNAME: '{% raw %}{{ username }}{% endraw %}'