---
controller_projects:
  - name: Demo Environment Tools 
    scm_type: git
    scm_url: https://github.com/corumj/demo-env-ansible
    scm_branch: master
    scm_clean: true
    description: Demo Environment repo with provisioning and demo management tools 
    organization: Default
    wait: true
    update: true

  - name: Linux Tasks
    scm_type: git
    scm_url: https://github.com/corumj/ansible-linux-tasks
    scm_branch: platform
    scm_clean: true
    description: Linux playbooks and roles for demo 
    organization: Default
    wait: true
    update: true

  - name: Windows Tasks
    scm_type: git
    scm_url: https://github.com/corumj/ansible-windows-admin-tasks
    scm_branch: master
    scm_clean: true
    description: Windows playbooks and roles for demo 
    organization: Default
    wait: true
    update: true

  - name: ServiceNow Tasks
    scm_type: git
    scm_url: https://github.com/corumj/ansible-servicenow-demo
    scm_branch: aap2
    scm_clean: true
    description: ServiceNow playbooks and roles for demo 
    organization: Default
    wait: true
    update: true