---
controller_workflows:
  - name: "[Demo] Deploy GoAddr Application"
    description: Workflow to deploy GoAddr App 
    extra_vars: {}
    state: present
    organization: Default
    simplified_workflow_nodes:
      - all_parents_must_converge: false 
        identifier: frontend-deploy
        unified_job_template: "[ Windows ] Deploy GoAddr Frontend"
        limit: demo_app_frontend
      - all_parents_must_converge: false 
        identifier: postgres 
        unified_job_template: "[ Linux ] Galaxy Role: Setup Postgresql"
        limit: demo_app_database
      - all_parents_must_converge: false 
        identifier: goaddr-api 
        unified_job_template: "[ Linux ] Deploy GoAddr API"
        limit: demo_app_backend
      - all_parents_must_converge: false 
        identifier: timesync 
        unified_job_template: "[ Linux ] RHEL System Role timesync"
        limit: demo_app_backend,demo_app_database
        success_nodes:
          - goaddr-api 
          - postgres
      - all_parents_must_converge: false 
        identifier: crypto
        unified_job_template: "[ Linux ] RHEL System Role crypto policy"
        limit: demo_app_backend,demo_app_database
        success_nodes:
          - timesync 
      - all_parents_must_converge: false 
        identifier: configure-iis
        unified_job_template: "[ Windows ] Configure IIS"
        limit: demo_app_frontend
        success_nodes:
          - frontend-deploy
      - all_parents_must_converge: false 
        identifier: configure-dns
        unified_job_template: "[ Windows ] Configure DNS client"
        limit: demo_app_frontend
        success_nodes:
          - configure-iis
      - all_parents_must_converge: false 
        identifier: linux-database-instance
        unified_job_template: "1. Provision"
        extra_data:
          survey_group_name: app_database
          survey_server_name: database 
          survey_server_env: dev 
          survey_server_os: linux 
        success_nodes:
          - crypto
      - all_parents_must_converge: false 
        identifier: linux-back-end-instance
        unified_job_template: "1. Provision"
        extra_data:
          survey_group_name: app_backend
          survey_server_name: backend 
          survey_server_env: dev 
          survey_server_os: linux 
        success_nodes:
          - crypto
      - all_parents_must_converge: false 
        identifier: windows-front-end-instance
        unified_job_template: "1. Provision"
        extra_data:
          survey_group_name: app_frontend
          survey_server_name: frontend 
          survey_server_env: dev 
          survey_server_os: windows 
        success_nodes:
          - configure-dns