---
- name: Listen for events from journald
  hosts: tag_journald_nodes

  ## Define our source for events

  sources:
    - ansible.eda.journald:
        match: "PRIORITY=3"

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: 1=1

  ## Define the action we should take should the condition be met

      action:
        debug:
        # run_job_template:
        #   name: EDA - Webhook Response
        #   organization: Default 
