---
- name: Listen for events in a Kafka Stream
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.kafka:
        host: ec2-18-217-148-42.us-east-2.compute.amazonaws.com
        port: 9092
        topic: ansible 
        check_hostname: False

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.message == "Ansible is super cool"

  ## Define the action we should take should the condition be met

      action:
        run_job_template:
          name: EDA - Webhook Response
          organization: Default 
          # job_args:
          #   extra_vars:
          #     ansible_eda: "{{ event }}"