---
- name: Listen for events in a Kafka Stream
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.kafka:
        host: my-cluster-kafka-tls-bootstrap-kafka.apps.cluster-w8qsl.w8qsl.sandbox1817.opentlc.com
        port: 9093
        topic: ansible-topic 
        check_hostname: False

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.message == "Ansible is super cool"

  ## Define the action we should take should the condition be met

      action:
        run_job_template:
          name: EDA - Webhook Response
          organization: Default 
          # job_args:
          #   extra_vars:
          #     ansible_eda: "{{ event }}"