---
- name: "Create {{ item.username }} admin roles for {{ item.username }}-org "
  ansible.controller.role:
    user: "{{ item.username }}"
    organizations: "{{ item.username }}-org"
    role: admin 
    state: present 
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://controller.{{ top_level_domain }}"
    validate_certs: true