---
- name: "Create {{ item.username }}'s Organizations"
  ansible.controller.organization: 
    name: "{{ item.username }}-org"
    description: "Organization for {{ item.username }}" 
    state: present 
    controller_username: "admin"
    controller_password: "{{ admin_password }}"
    controller_host: "https://controller.{{ top_level_domain }}"
    validate_certs: true